"""empty message

Revision ID: 31ee0af82637
Revises: 20fab6f594ea
Create Date: 2020-03-04 10:02:43.661359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ee0af82637'
down_revision = '20fab6f594ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Event', ['id'])
    op.create_unique_constraint(None, 'Event_Ticket', ['id'])
    op.create_unique_constraint(None, 'FeedbackAnswer', ['id'])
    op.create_unique_constraint(None, 'FeedbackQuestion', ['id'])
    op.create_unique_constraint(None, 'Purchasable', ['id'])
    op.create_unique_constraint(None, 'Purchasable_TicketClass', ['id'])
    op.create_unique_constraint(None, 'Ticket', ['id'])
    op.create_unique_constraint(None, 'TicketClass', ['id'])
    op.drop_constraint('User_isAdmin_key', 'User', type_='unique')
    op.create_unique_constraint(None, 'User', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.create_unique_constraint('User_isAdmin_key', 'User', ['isAdmin'])
    op.drop_constraint(None, 'TicketClass', type_='unique')
    op.drop_constraint(None, 'Ticket', type_='unique')
    op.drop_constraint(None, 'Purchasable_TicketClass', type_='unique')
    op.drop_constraint(None, 'Purchasable', type_='unique')
    op.drop_constraint(None, 'FeedbackQuestion', type_='unique')
    op.drop_constraint(None, 'FeedbackAnswer', type_='unique')
    op.drop_constraint(None, 'Event_Ticket', type_='unique')
    op.drop_constraint(None, 'Event', type_='unique')
    # ### end Alembic commands ###
