"""empty message

Revision ID: 60ccae1fcaee
Revises: 7c97d12e639f
Create Date: 2020-03-23 14:12:34.588864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ccae1fcaee'
down_revision = '7c97d12e639f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Event_Ticket_ticket_id_fkey', 'Event_Ticket', type_='foreignkey')
    op.drop_constraint('Event_Ticket_event_id_fkey', 'Event_Ticket', type_='foreignkey')
    op.create_foreign_key(None, 'Event_Ticket', 'Event', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Event_Ticket', 'Ticket', ['ticket_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Event_Ticket', type_='foreignkey')
    op.drop_constraint(None, 'Event_Ticket', type_='foreignkey')
    op.create_foreign_key('Event_Ticket_event_id_fkey', 'Event_Ticket', 'Event', ['event_id'], ['id'])
    op.create_foreign_key('Event_Ticket_ticket_id_fkey', 'Event_Ticket', 'Ticket', ['ticket_id'], ['id'])
    # ### end Alembic commands ###
