"""empty message

Revision ID: 7c97d12e639f
Revises: 9351ab7f03a5
Create Date: 2020-03-21 13:45:07.021568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c97d12e639f'
down_revision = '9351ab7f03a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Event', ['id'])
    op.create_unique_constraint(None, 'Event_Ticket', ['id'])
    op.create_unique_constraint(None, 'FeedbackAnswer', ['id'])
    op.create_unique_constraint(None, 'FeedbackQuestion', ['id'])
    op.create_unique_constraint(None, 'Purchasable', ['id'])
    op.create_unique_constraint(None, 'Purchasable_TicketClass', ['id'])
    op.create_unique_constraint(None, 'Ticket', ['id'])
    op.create_unique_constraint(None, 'TicketClass', ['id'])
    op.create_unique_constraint(None, 'User', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'TicketClass', type_='unique')
    op.drop_constraint(None, 'Ticket', type_='unique')
    op.drop_constraint(None, 'Purchasable_TicketClass', type_='unique')
    op.drop_constraint(None, 'Purchasable', type_='unique')
    op.drop_constraint(None, 'FeedbackQuestion', type_='unique')
    op.drop_constraint(None, 'FeedbackAnswer', type_='unique')
    op.drop_constraint(None, 'Event_Ticket', type_='unique')
    op.drop_constraint(None, 'Event', type_='unique')
    # ### end Alembic commands ###
